### ISSUE TITLE
Implement `encodeToString`

### ISSUE THREAD

**Issue by Wavesonics** [akuleshov7/ktoml#151]
This would be really useful in general

**Comment by akuleshov7** [comment]
Yeah, @NightEule5 and I started this work already: https://github.com/akuleshov7/ktoml/issues/11

There is mostly everything done - this should take 1-2 weekends and 5-6 bottles of beer to implement

**Comment by akuleshov7** [comment]
By the way - why do you need encoding of TOML? Usually TOML is used as a config-file format and decoder is needed. Why do you want to use encoder?

**Comment by Wavesonics** [comment]
My use case the program will have some UI to change some of the values

**Comment by akuleshov7** [comment]
So you plan to generate files in TOML format? Got it

**Comment by Wavesonics** [comment]
Ya, if you guys have a branch up for the encoding I wouldn't mind contributing.

**Comment by akuleshov7** [comment]
> Ya, if you guys have a branch up for the encoding I wouldn't mind contributing.

Everything is merged - AST enhancements, annotations for encoding -> so no branch is up there. We can easily split the remaining logic and give you some part of it if you wish :)

**Comment by NightEule5** [comment]
I have a draft implementation up on my fork now. I've gotta test and debug still, it's not quite working. Progress is being made :)

**Comment by Wavesonics** [comment]
@NightEule5 any progress on this? if there's a branch somewhere I wouldn't mind helping out
