### ISSUE TITLE
Update Readme: add info about serialization 

### ISSUE THREAD

**Issue by akuleshov7** [akuleshov7/ktoml#156]
We need to:
- cover in readme missing serialization features
- add examples of serialization (create two sections instead existing one: serialization and deserialization)

**Comment by akuleshov7** [comment]
partially added in #157

**Comment by NightEule5** [comment]
I realized in the deserialization example the `InlineTable` class isn't defined:

```kotlin
@Serializable
data class Table2(
    val someNumber: Long,
    @SerialName("akuleshov7.com")
    val inlineTable: InlineTable,
    val otherNumber: Double
)
```
