### ISSUE TITLE
Support iosSimulatorArm64

### ISSUE THREAD

**Issue by jeremyKim** [akuleshov7/ktoml#185]
Hi.
I wrote test code in commonMainTest directory and tried to test on iosSimulator.
But I met error like below.
It seems like ktoml does not support iosSimulator yet.

Do you have any plan to support simulator? 
I would appreciate if you could teach me any workaround.

`
iosSimulatorArm64Main: Could not resolve com.akuleshov7:ktoml-core:0.4.1
`
`
iosSimulatorArm64Test: Could not resolve com.akuleshov7:ktoml-core:0.4.1.
`

**Comment by akuleshov7** [comment]
That's a one line change, @jeremyKim 😄

**Comment by akuleshov7** [comment]
#186

**Comment by jeremyKim** [comment]
@akuleshov7 Thank you for your quick response. I really appreciate it :)
