### ISSUE TITLE
Java compatibility is not properly set to Java 8

### ISSUE THREAD

**Issue by ty1824** [akuleshov7/ktoml#191]
I attempted to use this library in a project with Java 8 and got the classic class file version error:

`com/akuleshov7/ktoml/Toml has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

The release action uses Java 11 and build.gradle does not properly specify the compatibility version. I believe, based on personal testing & research, that the following configuration is not enough:
```
jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "1.8"
        }
}
```

There are several ways to do it, but I believe the easiest with more recent Kotlin Gradle plugins is:

```
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}
```

**Comment by akuleshov7** [comment]
Hey! Thank you for the report and suggestion.

Can you please also add a snippet of how you call ktoml from Java please? So I will copy-paste it while testing the solution

**Comment by akuleshov7** [comment]
@saschpe have you used ktoml with Java after your #182 ? Any issues?

**Comment by ty1824** [comment]
> Can you please also add a snippet of how you call ktoml from Java please? So I will copy-paste it while testing the solution

Sorry I never replied to this, I see you have merged a fix. I'll try to build/test and let you know what I find!

**Comment by ty1824** [comment]
Having a hard time trying to build/publish to local, `./gradlew :ktoml-core:publishJvmPublicationToMavenLocal` fails with "Publication jvm is skipped on current host"

I'll try tweaking config to see if I can get this to work.


Update: I made a change to `PublishingConfiguration.kt` to allow publishing to maven local
Line 72: 
`.matching { it.publication == targetPublication }`
to
`.matching { it !is PublishToMavenLocal && it.publication == targetPublication }`

**Comment by ty1824** [comment]
Was able to get this working in my project :) Thanks for the quick update!
