### ISSUE TITLE
Compatibility issues with windows7

### ISSUE THREAD

**Issue by willflier** [akuleshov7/ktoml#193]
I got the error "The procedure entry point EnumDynamicTimeZoneInformation could not be located in the dynamic link library ADVAPI32.dll" in Win7
I found that it was caused by [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime/blob/4895b491c1d7dd7c356b7a3acd94c5ce89ef9d3a/core/native/cinterop/cpp/windows.cpp)

Are there any other alternatives?

**Comment by akuleshov7** [comment]
Reported to https://github.com/Kotlin/kotlinx-datetime/issues/262

**Comment by akuleshov7** [comment]
@willflier got an answer from JB in https://github.com/Kotlin/kotlinx-datetime/issues/262
