### ISSUE TITLE
Exception when decoding map

### ISSUE THREAD

**Issue by jakubgwozdz** [akuleshov7/ktoml#234]
Having this code:
```kotlin
@Serializable
private data class TestData(
    val text: String,
    val map: Map<String, String>,
    val number: Int,
)
fun main() {
    val data = TestData(text = "text value", number = 7321, map = mapOf("a" to "b"))
    val encoded = Toml.encodeToString(data)
    println("=====\n$encoded\n=====")
    val decoded: TestData = Toml.decodeFromString(encoded) // throws MissingRequiredPropertyException
}
```
The output is this:
```
=====
text = "text value"
number = 7321

[map]
    a = "b"
=====
Exception in thread "main" com.akuleshov7.ktoml.exceptions.MissingRequiredPropertyException: Invalid number of key-value arguments provided in the input for deserialization. Missing required property <0> from class <kotlin.collections.LinkedHashMap> in the input. (In your deserialization class you have declared this field, but it is missing in the input)
	at com.akuleshov7.ktoml.decoders.TomlMainDecoder.checkMissingRequiredProperties(TomlMainDecoder.kt:192)
	at com.akuleshov7.ktoml.decoders.TomlMainDecoder.iterateOverStructure(TomlMainDecoder.kt:243)
	at com.akuleshov7.ktoml.decoders.TomlMainDecoder.beginStructure(TomlMainDecoder.kt:212)
```

Encoding works perfectly well and toml content is generated without problems, but decoding this content back - well, we're not there yet :)

**Comment by akuleshov7** [comment]
will be investigated this month

**Comment by akuleshov7** [comment]
thank you for your report and sorry for a long delay!

**Comment by y9san9** [comment]
Still having the issue, is there any workaround? Really need to deserialize libs.versions.toml

**Comment by akuleshov7** [comment]
@y9san9 sorry for a stupid question, what is the datastucture in toml reflects Maps? Cannot find a simple example.

**Comment by akuleshov7** [comment]
Hm, but it's a little bit weird actually: 
```
library = "1.0.0"
kotlin = "2.0.0"
```

is not a Map... It's a number of properties in Toml specification.

**Comment by akuleshov7** [comment]
> So how could I deserialize that?
> 
> And also that:
> 
> ```toml
> coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
> ```
> 
> All the solutions I found did that using Map

hm, let me look into the spec of TOML

**Comment by y9san9** [comment]
A list of inline tables?

**Comment by y9san9** [comment]
Sorry, I mentioned earlier that I don't know what names of the libraries will be. I want to parse them and only after that I could tell the names.

**Comment by y9san9** [comment]
In Json when you don't know class layout you would also use Map<String, JsonElement>

**Comment by akuleshov7** [comment]
> Sorry, as I mentioned earlier that I don't know what names of the libraries will be. I want to parse them and only after that I could tell the names.

Got it, so you need to parse properties without explicit naming, and you need to decode it to some map of strings. I do not have an idea of how to support it now, as it is violating TOML spec, but I will think...

**Comment by akuleshov7** [comment]
> Why is it violating TOML specs? It's how Version Catalogs work :)

I mean that the idea of TOML is that you know the names of the properties. That's why this structure: 

```
a = 1
```

is a NAMED key-value property https://toml.io/en/v1.0.0#keyvalue-pair

It will be a different story to decode the following code:

```
a = 1
b = 2
``` 

to a map ("a" to "1", "b" to "2"), because the original idea is about named keys.

**Comment by akuleshov7** [comment]
BUT! Ktoml itself has multiple extensions to the original idea of TOML, so probably we can think of something we can do here. Especially when we encode these values to a Map.

**Comment by akuleshov7** [comment]
Initial implementation is done for simple map: https://github.com/akuleshov7/ktoml/pull/246
@jakubgwozdz @y9san9

**Comment by akuleshov7** [comment]
Nested Maps (nested tables) done in #252

**Comment by akuleshov7** [comment]
Released
