### ISSUE TITLE
Why this library is not mentioned in official toml site?

### ISSUE THREAD

**Issue by teras** [akuleshov7/ktoml#249]
I find your library interesting. I am thinking though, why isn't mentioned in https://github.com/toml-lang/toml/wiki#implementations

I think it is a good alternative and should be mentioned there. Or I can try to make a PR myself, but maybe from the original authors should be more important.

What do you think?

**Comment by akuleshov7** [comment]
@teras very good question! 
The only problem that we still do not support all 100% functionality of TOML. 

But may be it will be a good point to add it, as there is not much alternatives in Kotlin.

**Comment by akuleshov7** [comment]
@teras it's even not a PR, just wiki editing, done :)

**Comment by teras** [comment]
good job! Let's close this issue then!
