### ISSUE TITLE
Linux arm64

### ISSUE THREAD

**Issue by zt64** [akuleshov7/ktoml#264]
Hi,
Would it be possible to add compilation for linux arm64?

**Comment by akuleshov7** [comment]
Sorry for a long response - it can be done easily with a single line in build.gradle.kts

**Comment by zt64** [comment]
I've gone ahead and opened a PR enabling arm64 compilation #270

**Comment by akuleshov7** [comment]
> I've gone ahead and opened a PR enabling arm64 compilation #270

will be released this week

**Comment by orchestr7** [comment]
@zt64 released in 0.5.2. Sorry for the delay
