### ISSUE TITLE
Looks like toml does not support enums. But ktoml supports, need to make it configurable

### ISSUE THREAD

**Issue by akuleshov7** [akuleshov7/ktoml#36]
Enums should beprocessed only with a config enabled
Entry point: KtomlConf

**Comment by bishiboosh** [comment]
@akuleshov7 not sure I totally agree with this one, JSON does not have the concept of enums either, but enums are still serialized  in JSON with their name. Enums are only a way to store an info deserialized from the TOML data.

**Comment by akuleshov7** [comment]
I wanted to make this configurable, but yes, it looks like a bad idea (as mentioned by @bishiboosh in the above comment)
