### ISSUE TITLE
Multiline literal strings

### ISSUE THREAD

**Issue by akuleshov7** [akuleshov7/ktoml#46]
Multi-line literal strings are surrounded by three single quotes on each side and allow newlines. Like literal strings, there is no escaping whatsoever. A newline immediately following the opening delimiter will be trimmed. All other content between the delimiters is interpreted as-is without modification.
```
regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

**Comment by bishiboosh** [comment]
@akuleshov7 can I try to take a stab at this ? Don't know if you've started looking at it yet (and don't know if I can do it quickly) but I'd like to try

**Comment by bishiboosh** [comment]
(I have a WIP right now, as soon as work clears up a little bit I'll try to go back to it)

**Comment by akuleshov7** [comment]
Got it, removed myself

**Comment by BOOMeranGG** [comment]
Hi there! I see that there are no updates. I almost completed this issue, MR will be soon.

**Comment by akuleshov7** [comment]
> Hi there! I see that there are no updates. I almost completed this issue, MR will be soon.

the only thing I have is this test :D

```
class MultilineStrings {
    @Test
    fun positiveSimpleParsing() {
        val string = """
            [[fruits]]
            a = '''
                b = 4
            '''
        """.trimIndent()

        val parsedToml = tomlParser.parseString(string)
        parsedToml.prettyPrint()
        assertEquals(
            """
                | - TomlFile (rootNode)
        """.trimMargin(),
            parsedToml.prettyStr()
        )
    }
}
```

**Comment by akuleshov7** [comment]
@BOOMeranGG may be take it into the nearest release? I plan it in 1-2 weeks?

**Comment by BOOMeranGG** [comment]
Ok. One question: why was #8 closed? Do we need to support multiline literal and basic strings?
