### ISSUE TITLE
A good idea is to use annotation processing with reflekt for the configuration

### ISSUE THREAD

**Issue by akuleshov7** [akuleshov7/ktoml#79]
https://github.com/JetBrains-Research/reflekt

**Comment by Peanuuutz** [comment]
I think `@SerialInfo` from kotlinx.serialization could make it, like this:
```kotlin
@SerialInfo
@Target(AnnotationTarget.PROPERTY)
public annotation class Comment(vararg val texts: String)

// In <?>Encoder
fun comment(descriptor: SerialDescriptor, index: Int) {
    descriptor.getElementAnnotations(index)
        .filterIsInstance<Comment>()
        .let {
            if (it.isEmpty())
                emptyArray<String>()
            else
                it[0].texts // As Comment is not @Repeatable, we take the first
        }
        .forEach { emitComment(it) } // functional YES!
}
```

**Comment by NightEule5** [comment]
Yes, I think this is covered by kotlinx.serialization already. I'm not sure what functionality Reflekt would provide that we don't have access to, but I could be missing something

**Comment by akuleshov7** [comment]
Yeah, it looks so. I actually wanted to add some custom annotations for compile time reflection, but yes Kotlinx.serialization already has mostly everything we need. May be we will use reflekt for something else next time :)
