### ISSUE TITLE
Allow empty files

### ISSUE THREAD

**Issue by JakeWharton** [akuleshov7/ktoml#94]
Currently, this logic:

https://github.com/akuleshov7/ktoml/blob/cc6e05a5af8c93443a962e84807205b3204db9fd/ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt#L180-L183

forbids the parsing of empty files.

First, consider the official TOML ABNF: https://github.com/toml-lang/toml/blob/1.0.0/toml.abnf. This format definition allows an empty file through a single `expression` consisting of white space (`ws`) of zero characters (`*wschar`).

Second, as far as this library is concerned, if all my properties have default values then an empty parse should return the default instance.
```kotlin
@Serializable
data class Foo(val name: String = "Jake")

val expected = Foo()
val actual = Toml.decodeFromString(Foo.serializer(), "")
assert(expected == actual)
```

I have a real-world use where all of my top-level properties have sane defaults bound in the model and all of my supported tables are optional (and thus have `null` defaults in the model). Currently this fails to parse because of this check.

**Comment by akuleshov7** [comment]
Hi @JakeWharton , thank you for this good note, sounds reasonable. We can workaround and let the work with empty toml files. will try to take it into the nearest release.

**Comment by akuleshov7** [comment]
Haha, we even have a test for empty toml:

```
class EmptyTomlTest {
    @Test
    fun emptyToml() {
        assertFailsWith<InternalDecodingException> {
            Toml().decodeFromString<Config>(
                """            
             
             
                """.trimIndent()
            )
        }

        assertFailsWith<InternalDecodingException> {
            Toml().decodeFromString(
                "".trimIndent()
            )
        }
    }
}

```

**Comment by akuleshov7** [comment]
@JakeWharton that was easy 😄  https://github.com/akuleshov7/ktoml/pull/95
